name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: https://org1f2ad44c.crm.dynamics.com
        user-name: demodev@pmgevents.onmicrosoft.com
        password-secret: ${{ secrets.password }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: https://org1f2ad44c.crm.dynamics.com
        user-name: demodev@pmgevents.onmicrosoft.com
        password-secret: ${{ secrets.password }}
        solution-name: ToyotaVehicleQualitySolution
        solution-output-file: out/exported/ToyotaSolution.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/ToyotaSolution.zip
        solution-folder: out/solutions/ToyotaSolution
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/ToyotaSolution
        solution-target-folder: solutions/ToyotaSolution
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
