name: release-solution-to-prod
# prepare for releasing to prod:
#   convert solution to managed (using a build PowerPlatform environment for the conversion)
#   upload the solution to the GitHub artifacts and deploy to the PROD environment

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  convert-to-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: solutions/ToyotaALM
        solution-file: out/solutions/ToyotaALM.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: https://org8ea26093.crm.dynamics.com
        user-name: demodev@pmgevents.onmicrosoft.com
        password-secret: ${{ secrets.password }}
        solution-file: out/solutions/ToyotaALM.zip
        force-overwrite: true
        publish-changes: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: https://org8ea26093.crm.dynamics.com
        user-name: demodev@pmgevents.onmicrosoft.com
        password-secret: ${{ secrets.password }}
        solution-name: ToyotaALM
        managed: true
        solution-output-file: out/ship/ToyotaALM.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: out/ship/ToyotaALM.zip

  release-to-staging:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: out/release/

    - run: get-childitem .\out\release\

    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: https://org8ea26093.crm.dynamics.com
        user-name: demodev@pmgevets.onmicrosoft.com
        password-secret: ${{ secrets.password }}
        solution-file: out/release/toyotaALM.zip
        force-overwrite: true
        publish-changes: true
